version: '3.7'
services:
#  nginx:
#    build: images/nginx
#    command: nginx -g "daemon off;"
#    links:
#      - activity
#    ports:
#      - "8084:80"
#    volumes:
#      - ./services:/var/www/html
#    networks:
#      internal-network:
#        aliases:
#          - nginx-playground.service

  activity:
    build: services/activity
    volumes:
      - ./services/activity:/var/www/html/activity
    working_dir: /var/www/html/activity/public
    command: php -S 0.0.0.0:9000 index.php
    links:
      - db
      - cache
    ports:
      - "9006:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      internal-network:
        aliases:
          - php-playground.service

  calendar:
    build: services/calendar
    volumes:
      - ./services/calendar:/var/www/html/calendar
    working_dir: /var/www/html/calendar/public
    command: php -S 0.0.0.0:9000 index.php
    links:
      - db
      - cache
    ports:
      - "9007:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      internal-network:
        aliases:
          - calendar.service

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      internal-network:
        aliases:
          - db-playground.service

  cache:
    image: memcached:1.6-alpine
    networks:
      internal-network:
        aliases:
          - cache-playground.service

networks:
  internal-network:
    name: internal-network
