version: '3.7'
services:
  krakend:
    image: devopsfaith/krakend:latest
    command: run --config /opt/krakend/krakend.json
    links:
      - nginx
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./images/krakend/config/krakend.json:/opt/krakend/krakend.json
    networks:
      internal-network:
        aliases:
          - krakend-playground.service

  nginx:
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - activity
      - calendar
    ports:
      - "8081:8081"
      - "8082:8082"
    expose:
      - "8081"
      - "8082"
    volumes:
      - ./services/activity/public:/var/www/html/activity/public:ro
      - ./services/calendar/public:/var/www/html/calendar/public:ro
    networks:
      internal-network:
        aliases:
          - nginx-playground.service

  activity:
    build: services/activity
    volumes:
      - ./services/activity:/var/www/html/activity
    working_dir: /var/www/html/activity
    command: php-fpm
    links:
      - db
      - cache
    expose:
      - "9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      internal-network:
        aliases:
          - activity.service

  calendar:
    build: services/calendar
    volumes:
      - ./services/calendar:/var/www/html/calendar
    working_dir: /var/www/html/calendar
    command: php-fpm
    links:
      - db
      - cache
    expose:
      - "9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      internal-network:
        aliases:
          - calendar.service

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      internal-network:
        aliases:
          - db-playground.service

  cache:
    image: memcached:1.6-alpine
    networks:
      internal-network:
        aliases:
          - cache-playground.service

networks:
  internal-network:
    name: internal-network
